### ISSUE TITLE
PROCESSOR: Throws exception when creating a new scenario with text in the description field

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#25]
New scenario screen in PROCESSOR throws an exception when you save text entered in the scenario description field. Here is the offending line in code:

string strProjDir = ((frmMain)this.ParentForm.ParentForm).frmProject.uc_project1.m_strProjectDirectory;

I believe the second ParentForm is what is null. Any ideas @lpotts ?

{System.NullReferenceException: Object reference not set to an instance of an object.
   at FIA_Biosum_Manager.uc_scenario_notes.SaveScenarioNotes() in C:\workspace\BioSum\Fia-Biosum-Manager\src\uc_scenario_notes.cs:line 140
   at FIA_Biosum_Manager.frmProcessorScenario.SaveRuleDefinitions() in C:\workspace\BioSum\Fia-Biosum-Manager\src\frmProcessorScenario.cs:line 711
   at FIA_Biosum_Manager.frmProcessorScenario.CheckToSave() in C:\workspace\BioSum\Fia-Biosum-Manager\src\frmProcessorScenario.cs:line 607
   at FIA_Biosum_Manager.frmProcessorScenario.frmProcessorScenario_FormClosing(Object sender, FormClosingEventArgs e) in C:\workspace\BioSum\Fia-Biosum-Manager\src\frmProcessorScenario.cs:line 954
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)}

**Comment by lbross** [comment]
Per @lpotts replace offending line with:
string strProjDir = frmMain.g_oFrmMain.frmProject.uc_project1.txtRootDirectory.Text.Trim();

No longer throwing exception. Will be included in next release.

**Comment by lbross** [comment]
Fixed in v5.7.0. Closing.
